version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket aws-sam-test01 --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
